require:
  - standard
  - rubocop-minitest
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - .bundle/**/*
    - .circleci/**/*
    - bin/**/*
    - vendor/**/*
    - pkg/**/*

Rails:
  Enabled: true
Minitest:
  Enabled: true
