# This workflow creates a release pull request whenever a change is pushed to 'main'.
# When the release pull request is merged into main, it will automatically create and tag a new
# release version.

name: Release automation
on:
  push:
    branches: [main]
jobs:
  release-please:
    name: Create a new release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: ruby
          package-name: omakase_search
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: false
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"style","section":"Styles","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"test","section":"Tests","hidden":false},
              {"type":"build","section":"Build System","hidden":false},
              {"type":"ci","section":"Continuous Integration","hidden":false}
            ]
          version-file: "lib/omakase_search/version.rb"
